name: Unified Release Build

on:
  push:
    tags:
      - "v*"

jobs:

  build-api:
    name: API Docker Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Try API build (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: test-api:${{ github.sha }}


  build-ui:
    name: UI Docker Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Try UI build (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          file: ./ui/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: test-ui:${{ github.sha }}


  docker-publish:
    name: Build & Push Multi-Arch Images
    runs-on: ubuntu-latest
    needs:
      - build-api
      - build-ui

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: registry.nimahosts.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # API IMAGE
      - name: Build & Push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            registry.nimahosts.com/hubo/firmware-registry-api:${{ github.ref_name }}
            registry.nimahosts.com/hubo/firmware-registry-api:latest

      # UI IMAGE
      - name: Build & Push UI
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          file: ./ui/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            registry.nimahosts.com/hubo/firmware-registry-ui:${{ github.ref_name }}
            registry.nimahosts.com/hubo/firmware-registry-ui:latest